(() => {
'use strict';
const $=s=>document.querySelector(s);
const message=$('#message'),answerBox=$('#answerBox');
let difficulty=1,score=0,streak=0,p=null,bundles=0,unpacked=0,selectedChoice=null,selectedHour=null,selectedMinute=null,last=[];
const rand=a=>a[Math.floor(Math.random()*a.length)];
const randInt=(a,b,s=10)=>a+Math.floor(Math.random()*(Math.floor((b-a)/s)+1))*s;
function generate(){let x,k,t=0;do{const type=Math.random()<.5?'minutesToTime':'timeToMinutes';if(type==='minutesToTime'){const m=difficulty===1?rand([60,90,120,150,180,200]):difficulty===2?randInt(70,240):randInt(70,360);x={type,minutes:m,label:`${m}분`}}else{const h=difficulty===3?rand([1,2,3,4,5]):rand([1,2,3]);const mins=difficulty===1?rand([0,30]):rand([0,10,20,30,40,50]);x={type,minutes:h*60+mins,hours:h,mins,label:mins===30?`${h}시간 반`:mins?`${h}시간 ${mins}분`:`${h}시간`}}k=`${type}-${x.minutes}`;t++}while(last.includes(k)&&t<20);last.push(k);if(last.length>6)last.shift();return x}
const maxBundles=()=>Math.floor(p.minutes/60);
function selectButton(box,value,setter){box.querySelectorAll('button').forEach(b=>b.classList.remove('selected'));const b=box.querySelector(`[data-value="${value}"]`);if(b)b.classList.add('selected');setter(value)}
function buildTimePickers(){const hb=$('#hourChoices'),mb=$('#minuteChoices');hb.innerHTML='';mb.innerHTML='';const max=Math.max(3,maxBundles()+1);for(let i=0;i<=max;i++){const b=document.createElement('button');b.type='button';b.className='choice-btn compact';b.dataset.value=i;b.textContent=i;b.addEventListener('click',()=>{selectButton(hb,i,v=>selectedHour=v);updateCheckVisibility()});hb.appendChild(b)}[0,10,20,30,40,50].forEach(v=>{const b=document.createElement('button');b.type='button';b.className='choice-btn compact';b.dataset.value=v;b.textContent=v;b.addEventListener('click',()=>{selectButton(mb,v,n=>selectedMinute=n);updateCheckVisibility()});mb.appendChild(b)})}
function updateCheckVisibility(){if(p.type==='minutesToTime')$('#checkBtn').hidden=!(bundles===maxBundles()&&selectedHour!==null&&selectedMinute!==null);else $('#checkBtn').hidden=!(unpacked===p.hours&&selectedChoice!==null)}
function renderBundles(){const list=$('#bundleList');list.innerHTML='';for(let i=0;i<bundles;i++){const e=document.createElement('div');e.className='hour-bundle';e.innerHTML='<span class="clock-icon">🧩</span><strong>60분</strong><small>한 묶음</small>';list.appendChild(e)}const left=p.minutes-bundles*60;$('#remainderValue').textContent=`${left}분`;$('#bundleBtn').disabled=left<60;$('#undoBtn').disabled=bundles===0;const done=bundles===maxBundles();$('#timeAnswerStep').hidden=!done;if(done){if(!$('#hourChoices').children.length)buildTimePickers();message.className='message success';message.textContent='더 이상 60분을 묶을 수 없어요. 이제 답을 직접 골라 보세요.'}else{$('#checkBtn').hidden=true}updateCheckVisibility()}
function makeMinuteChoices(){const correct=p.minutes,vals=new Set([correct]),offs=[10,20,30,60,-10,-20,-30,-60,90,-90];let g=0;while(vals.size<4&&g++<60){const v=correct+rand(offs);if(v>0&&v<=420)vals.add(v)}for(let v=30;vals.size<4;v+=30)if(correct+v<=420)vals.add(correct+v);const box=$('#answerChoices');box.innerHTML='';[...vals].sort(()=>Math.random()-.5).forEach(v=>{const b=document.createElement('button');b.type='button';b.className='choice-btn';b.dataset.value=v;b.textContent=`${v}분`;b.addEventListener('click',()=>{selectButton(box,v,n=>selectedChoice=n);message.className='message';message.textContent='답을 골랐어요. 정답을 확인해 보세요.';updateCheckVisibility()});box.appendChild(b)})}
function renderUnpacked(){const source=$('#timeSource'),visual=$('#timeVisual');source.innerHTML='';visual.innerHTML='';const remain=p.hours-unpacked;if(remain){const e=document.createElement('div');e.className='source-hour-card';e.innerHTML=`<span>🕐</span><strong>${remain}시간</strong><small>아직 풀지 않은 시간</small>`;source.appendChild(e)}if(p.mins){const e=document.createElement('div');e.className='source-rest-card';e.innerHTML=`<span>➕</span><strong>${p.mins}분</strong>`;source.appendChild(e)}for(let i=0;i<unpacked;i++){const e=document.createElement('div');e.className='given-hour unpacked';e.innerHTML='<span>🧩</span><strong>60분</strong><small>1시간을 풀었어요</small>';visual.appendChild(e)}if(p.mins){const e=document.createElement('div');e.className='given-rest';e.innerHTML=`<span>➕</span><strong>${p.mins}분</strong>`;visual.appendChild(e)}$('#unpackBtn').disabled=unpacked>=p.hours;$('#packBackBtn').disabled=unpacked===0;const done=unpacked===p.hours;$('#sumHint').hidden=!done;$('#answerChoices').hidden=!done;if(done){const parts=Array(p.hours).fill('60');if(p.mins)parts.push(p.mins);$('#sumHint').textContent=`${parts.join(' + ')} = ?`;if(!$('#answerChoices').children.length)makeMinuteChoices();message.className='message success';message.textContent='모두 60분으로 풀었어요. 이제 답을 골라 보세요.'}else{selectedChoice=null;$('#answerChoices').innerHTML='';$('#checkBtn').hidden=true}updateCheckVisibility()}
function render(){p=generate();bundles=0;unpacked=0;selectedChoice=selectedHour=selectedMinute=null;answerBox.hidden=true;$('#nextBtn').hidden=true;$('#checkBtn').hidden=true;$('#scoreText').textContent=score;$('#streakText').textContent=streak;$('#questionBig').textContent=p.label;$('#hourChoices').innerHTML='';$('#minuteChoices').innerHTML='';$('#timeAnswerStep').hidden=true;if(p.type==='minutesToTime'){$('#typePill').textContent='분 → 시간';$('#questionEyebrow').textContent='60분씩 묶어 볼까요?';$('#questionAsk').textContent='몇 시간 몇 분일까요?';$('#minutesGame').hidden=false;$('#timeGame').hidden=true;$('#sourceMinutes').textContent=p.label;message.className='message';message.textContent='60분을 하나씩 묶어 보세요.';renderBundles()}else{$('#typePill').textContent='시간 → 분';$('#questionEyebrow').textContent='1시간을 60분으로 풀어 볼까요?';$('#questionAsk').textContent='모두 몇 분일까요?';$('#minutesGame').hidden=true;$('#timeGame').hidden=false;$('#sumHint').hidden=true;$('#answerChoices').hidden=true;$('#answerChoices').innerHTML='';message.className='message';message.textContent='1시간을 하나씩 60분으로 바꿔 보세요.';renderUnpacked()}}
function finish(ok){if(!ok){streak=0;$('#streakText').textContent=0;message.className='message try';message.textContent='한 번 더 생각해 볼까요? 묶거나 풀어낸 모습을 천천히 살펴보세요.';return}score+=10+difficulty*5;streak++;$('#scoreText').textContent=score;$('#streakText').textContent=streak;message.className='message success';message.textContent='정답! 잘했어요! 🌟';const h=Math.floor(p.minutes/60),r=p.minutes%60;$('#answerText').textContent=p.type==='minutesToTime'?`${p.minutes}분 = ${h}시간${r?` ${r}분`:''}`:`${p.label} = ${p.minutes}분`;const parts=Array(h).fill('60분');if(r)parts.push(`${r}분`);$('#formulaText').textContent=`${parts.join(' + ')} = ${p.minutes}분`;answerBox.hidden=false;$('#checkBtn').hidden=true;$('#nextBtn').hidden=false}
function check(){if(p.type==='minutesToTime')finish(selectedHour===Math.floor(p.minutes/60)&&selectedMinute===p.minutes%60);else finish(selectedChoice===p.minutes)}
$('#bundleBtn').addEventListener('click',()=>{if(p.type==='minutesToTime'&&bundles<maxBundles()){bundles++;renderBundles()}});$('#undoBtn').addEventListener('click',()=>{if(bundles>0){bundles--;selectedHour=selectedMinute=null;$('#hourChoices').innerHTML='';$('#minuteChoices').innerHTML='';message.className='message';message.textContent='60분 묶음 하나를 다시 풀었어요.';renderBundles()}});$('#unpackBtn').addEventListener('click',()=>{if(p.type==='timeToMinutes'&&unpacked<p.hours){unpacked++;renderUnpacked()}});$('#packBackBtn').addEventListener('click',()=>{if(unpacked>0){unpacked--;message.className='message';message.textContent='60분 하나를 다시 1시간으로 돌렸어요.';renderUnpacked()}});document.querySelectorAll('.diff-btn').forEach(b=>b.addEventListener('click',()=>{difficulty=Number(b.dataset.diff);document.querySelectorAll('.diff-btn').forEach(x=>x.classList.remove('active'));b.classList.add('active');streak=0;render()}));$('#checkBtn').addEventListener('click',check);$('#resetBtn').addEventListener('click',()=>{bundles=unpacked=0;selectedChoice=selectedHour=selectedMinute=null;$('#hourChoices').innerHTML='';$('#minuteChoices').innerHTML='';$('#answerChoices').innerHTML='';answerBox.hidden=true;$('#nextBtn').hidden=true;$('#checkBtn').hidden=true;if(p.type==='minutesToTime')renderBundles();else renderUnpacked()});$('#nextBtn').addEventListener('click',render);try{render()}catch(e){console.error(e);message.className='message try';message.textContent='문제를 불러오지 못했어요. 페이지를 새로고침해 주세요.'}
})();